=== abbiee9/XML/XmlTutorial/WebContent/Note1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ap:schema xmlns:ap="http://www.w3.org/2001/XMLSchema" >


 <ap:element name="note">
    	
    

<ap:complexType> 	
  <ap:sequence>  
    <ap:element name="to" >
    	<ap:simpleType>
    	<ap:restriction base="ap:string">
    	<ap:pattern value="[a-z A-Z ]{5,10}"></ap:pattern>
    	</ap:restriction>
    	</ap:simpleType>
    </ap:element>
    <ap:element name="from" type="ap:string"/>
    <ap:element name="heading" type="ap:string"/>
    <ap:element name="body" type="ap:string"/>
  </ap:sequence>
  <ap:attribute name="lang" type="ap:string" use="required"/>
</ap:complexType>

</ap:element> 

<ap:element name="notes">
<ap:complexType>
  <ap:sequence>
   <ap:element ref="note" maxOccurs="3"></ap:element>
  </ap:sequence>
</ap:complexType>

</ap:element> 

</ap:schema>

=== abbiee9/XML/XmlTutorial/WebContent/Note.xml
<?xml version="1.0" encoding="UTF-8"?>

<notes xmlns:at="http://www.w3.org/2001/XMLSchema-instance" 
	at:noNamespaceSchemaLocation="Note1.xsd">
	
  <note lang="english">
  <to>Toveq</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
  
  </note>
  
  <note lang="english">
  <to>Tovew</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
  </note>
  
  <note lang="english">
  <to>Tovwwe</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend!</body>
  </note>
  
  
</notes>
